//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.30 at 12:11:03 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:schemas-microsoft-com:sql:SqlRowSet1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.microsoft.schemas.sql.sqlrowset1;
